# -*- coding: utf-8 -*-
"""23_MovieRecommendationSystemUsingSVD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dagmEe_IA63rEY0njnyIzWvKKQcZSHLm

#23 Movie Recommendation System Using SVD

### Importing the basic libraries
"""

import numpy as np
import pandas as pd

"""### Importing & Parsing the dataset as ratings and movies details"""

# Reading the ratings data
ratingData = pd.read_csv(
    "ratings.dat",
    sep="::",
    engine="python",
    names=["user_id","movie_id","rating","time"]
)
# Reading the movies data
movieData = pd.read_csv(
    "movies.dat",
    sep="::",
    engine="python",
    names=["movie_id","title","genre"],
    encoding="latin1"
)

# Printing the DataFrames
print(ratingData)
print(movieData)

"""### Create the ratings matrix of shape (m×u)"""

num_movies = ratingData.movie_id.max()
num_users = ratingData.user_id.max()

ratingMatrix = np.zeros((num_movies, num_users))
for row in ratingData.itertuples():
    ratingMatrix[row.movie_id-1, row.user_id-1] = row.rating
print(ratingMatrix)

"""### Subtract Mean off - Normalization"""

movie_mean = np.mean(ratingMatrix, axis=1)
normalizedMatrix = ratingMatrix - movie_mean.reshape(-1,1)
print(normalizedMatrix)

"""### Computing SVD"""

A = normalizedMatrix.T / np.sqrt(ratingMatrix.shape[0] - 1)
from sklearn.decomposition import TruncatedSVD

svd = TruncatedSVD(n_components=50)

movie_features = svd.fit_transform(normalizedMatrix)

"""### Calculate cosine similarity, sort by most similar and return the top N"""

def get_similar_movies(movie_matrix, movie_id, top_n=5):

    index = movie_id - 1
    movie_vector = movie_matrix[index]

    magnitude = np.linalg.norm(movie_matrix, axis=1)

    similarity = np.dot(movie_matrix, movie_vector) / (magnitude * magnitude[index])

    similarity[index] = -1

    similar_indexes = np.argsort(-similarity)[:top_n]

    return similar_indexes

"""### Select k principal components to represent the movies, a movie_id to find recommendations and print the top_n results"""

k = 50
movie_id = 43
top_n = 5

# Define movie_features by selecting the first k principal components from Vt
#movie_features = Vt[:, :k]

indexes = get_similar_movies(movie_features, movie_id, top_n)

print('Recommendations for Movie {0}: \n'.format(
movieData[movieData.movie_id == movie_id].title.values[0]))
for id in indexes + 1:
    print(movieData[movieData.movie_id == id].title.values[0])

"""# Movie Recommendation System Using SVD

## Objective

The objective of this project is to build a movie recommendation system
that suggests similar movies to users based on rating patterns using
Singular Value Decomposition (SVD).

## Dataset

This project uses the MovieLens dataset which contains:

- User ID
- Movie ID
- Rating
- Timestamp

The dataset helps in analyzing user preferences and movie ratings.

## Algorithm Used: Singular Value Decomposition (SVD)

SVD is a matrix factorization technique used in recommendation systems.

It decomposes the user–movie rating matrix into three matrices:

A = U × Σ × Vᵀ

This helps identify hidden relationships between users and movies
and predict missing ratings.


## Project Workflow

1. Import required libraries
2. Load movie and rating datasets
3. Create user–movie rating matrix
4. Normalize the rating matrix
5. Apply Singular Value Decomposition (SVD)
6. Compute cosine similarity between movies
7. Recommend similar movies

## Output

The system recommends movies similar to the selected movie
based on rating similarity.

Example:

Recommendations for Movie: Toy Story

1. Toy Story 2
2. Bug's Life
3. Monsters Inc
4. Finding Nemo
"""